#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 15 14:00:05 2020

@author: yuan
"""

import numpy as np


nd=np.arange(12).reshape(3,4)
nd

#combine
#np.concatenate()
np.concatenate((nd,nd), axis=0)
np.concatenate((nd,nd), axis=1)

#stack list into ndarray
a = np.arange(5);a
b = np.zeros(5);b
np.stack((a,b), axis=0)
np.stack((a,b), axis=1)
np.vstack((a,b))
np.hstack((a,b))

#split ndarray into list
a=np.random.rand(3, 4)
a.shape
np.split(a, 3, axis=0)#split into 3 parts by rows
np.split(a, 4, axis=1)#split into 4 parts by columns